import "@/styles/globals.css";

import { Vazir } from "@/assets/fonts/fonts";
import { Inter } from "next/font/google";

import Providers from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3Li",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${Vazir.variable} ${inter.variable} debug-screens`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
