import { Vazir } from "@/assets/fonts/fonts";
import "@/styles/globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import Providers from "./providers";

export const metadata = {
  title: "T3Li",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Vazir.variable} debug-screens font-vazir`}>
        <Providers>
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </Providers>
      </body>
    </html>
  );
}
